import { AuthNotificationsWrapper } from "@/modules/auth/components/auth-notifications-wrapper";
import { AuthProvider } from "@/modules/auth/hooks/auth-context";
import GlobalLoading from "@/modules/shared/components/global-loading";
import Header from "@/modules/shared/components/header";
import Notification from "@/modules/shared/components/notification";
import { LoadingProvider } from "@/modules/shared/hooks/loading-context";
import { NotificationProvider } from "@/modules/shared/hooks/notification-context";
import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </head>
      <body>
        <div className="container sm:m-1.5 sm:p-1 md:mx-auto md:m-2.5 md:p-1">
          <LoadingProvider>
            <AuthProvider>
              <GoogleOAuthProvider
                clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? ""}
              >
                <NotificationProvider>
                  <AuthNotificationsWrapper>
                    <Header />
                    {children}
                    <Notification />
                    <GlobalLoading />
                  </AuthNotificationsWrapper>
                </NotificationProvider>
              </GoogleOAuthProvider>
            </AuthProvider>
          </LoadingProvider>
        </div>
      </body>
    </html>
  );
}
